src/Entity/Cours.php
<?php

namespace App\Entity;

use App\Repository\CoursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CoursRepository::class)
 */
class Cours
{
    use TimestampableEntity;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $level;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $duration;

    /**
     * @ORM\OneToMany(targetEntity=Lesson::class, mappedBy="Cours")
     */
    private $lessons;

    /**
     * @ORM\OneToOne(targetEntity=CoursCardsImage::class, inversedBy="cours", cascade={"persist", "remove"})
     */
    private $MainImage;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resume;

    public function __construct()
    {
        $this->lessons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getDuration(): ?string
    {
        return $this->duration;
    }

    public function setDuration(string $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    /**
     * @return Collection|Lesson[]
     */
    public function getLessons(): Collection
    {
        return $this->lessons;
    }

    public function addLesson(Lesson $lesson): self
    {
        if (!$this->lessons->contains($lesson)) {
            $this->lessons[] = $lesson;
            $lesson->setCours($this);
        }

        return $this;
    }

    public function removeLesson(Lesson $lesson): self
    {
        if ($this->lessons->removeElement($lesson)) {
            // set the owning side to null (unless already changed)
            if ($lesson->getCours() === $this) {
                $lesson->setCours(null);
            }
        }

        return $this;
    }

    public function getMainImage(): ?CoursCardsImage
    {
        return $this->MainImage;
    }

    public function setMainImage(?CoursCardsImage $MainImage): self
    {
        $this->MainImage = $MainImage;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(?string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }
}

src/Entity/Lesson.php
<?php

namespace App\Entity;

use App\Repository\LessonRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=LessonRepository::class)
 */
class Lesson
{
    use TimestampableEntity;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $video;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity=Cours::class, inversedBy="lessons")
     */
    private $Cours;

    /**
     * @ORM\Column(type="integer")
     */
    private $order_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="boolean")
     */
    private $completed;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVideo(): ?string
    {
        return $this->video;
    }

    public function setVideo(string $video): self
    {
        $this->video = $video;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCours(): ?Cours
    {
        return $this->Cours;
    }

    public function setCours(?Cours $Cours): self
    {
        $this->Cours = $Cours;

        return $this;
    }

    public function getOrderId(): ?int
    {
        return $this->order_id;
    }

    public function setOrderId(int $order_id): self
    {
        $this->order_id = $order_id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCompleted(): ?bool
    {
        return $this->completed;
    }

    public function setCompleted(bool $completed): self
    {
        $this->completed = $completed;

        return $this;
    }
}

src/Controller/Front/HomeController.php
<?php

namespace App\Controller\Front;

use App\Entity\Cours;
use App\Repository\CoursRepository;
use App\Repository\LessonRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home", methods={"GET"})
     */
    public function index(): Response
    {
        return $this->render('home/index.html.twig');
    }

    /**
     * @Route("/gallery", name="gallery", methods={"GET"})
     */
    public function gallery(): Response
    {
        return $this->render('home/gallery.html.twig');
    }

    /**
     * @Route("/events", name="events", methods={"GET"})
     */
    public function events(): Response
    {
        return $this->render('home/events.html.twig');
    }

    /**
     * @Route("/courses", name="courses", methods={"GET"})
     */
    public function courses(Request $request, CoursRepository $repository, PaginatorInterface $paginator): Response
    {   
        $queryBuilder = $repository->findByDesc(); 

        $pagination = $paginator->paginate(
            $queryBuilder, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            8/*limit per page*/
        );

        return $this->render('home/courses.html.twig', ['cours' => $pagination]);
    }

    /**
     * @Route("courses/{id}", name="show_cours", methods={"GET"})
     */
    public function show(Cours $cour): Response
    {
        return $this->render('home/cours.html.twig', [
            'cour' => $cour,
        ]);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Cours;
use App\Repository\CoursRepository;
use App\Repository\LessonRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home", methods={"GET"})
     */
    public function index(): Response
    {
        return $this->render('home/index.html.twig');
    }

    /**
     * @Route("/gallery", name="gallery", methods={"GET"})
     */
    public function gallery(): Response
    {
        return $this->render('home/gallery.html.twig');
    }

    /**
     * @Route("/events", name="events", methods={"GET"})
     */
    public function events(): Response
    {
        return $this->render('home/events.html.twig');
    }

    /**
     * @Route("/courses", name="courses", methods={"GET"})
     */
    public function courses(Request $request, CoursRepository $repository, PaginatorInterface $paginator): Response
    {   
        $queryBuilder = $repository->findAll();     

        $pagination = $paginator->paginate(
            $queryBuilder, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            10/*limit per page*/
        );

        return $this->render('home/courses.html.twig', ['cours' => $pagination]);
    }

    /**
     * @Route("courses/{id}", name="show_cours", methods={"GET"})
     */
    public function show(Cours $cour): Response
    {
        return $this->render('home/cours.html.twig', [
            'cour' => $cour,
        ]);
    }
}

templates/home/cours.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cours{% endblock %}

{% block stylesheets %}
<script src="https://kit.fontawesome.com/1596c4b58a.js" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
{{ parent() }}
{% endblock %}


{% block body %}
    {# divider  #}
    <div class="divider"></div>
    {# content  #}
    <div class="container">
        <div class="mb-5 mt-5" style="max-width:700px;object-fit:cover;display:block;margin:auto;">
            <img src="{{ uploaded_asset(cour.mainImage.src) }}" alt="{{ cour.mainImage.alt }}" style="display:block;margin:auto;width:100%;"/>
        </div>
        <div class="d-flex justify-content-start">
            <a href="{{ path('courses') }}" type="button" class="btn btn-secondary"><i class="fas fa-chevron-left"></i> Liste ds Cours </a>
        </div>
        {# titre #}
        <h1 class="text-centered mb-3">
        {{ cour.titre }}
        {% if is_granted("ROLE_ADMIN") %}
        <a href="{{ path('cours_edit', {id:cour.id}) }}" class="btn btn-warning">Modifier</a>
        {% endif %}
        </h1>
        {# infos  #}
        <div class="row justify-content-center mb-4">
            <div class="col-1">
                <i class="far fa-clock"></i> <span>{{ cour.duration }}</span>
            </div>
            <div class="col-2">
                <i class="fas fa-signal"></i> <span>{{ cour.level }}</span>
            </div>
        </div>
        {# content #}
        {% if cour.description == "" %}
        <p class="text-justify mb-5">{{ cour.description | raw }}</p>
        {% else %}
        {# alert #}
        <div class="alert alert-warning mt-5 mb-5" role="alert">
        Description en préparation
        </div>
        {% endif %}
        {% if cour.lessons is not empty %}
        <div class="d-flex justify-content-center">
            <a href="{{ path('lesson_show', { 'slug' : cour.slug, 'order' : 1}) }}" class="btn btn-primary mb-5">Commencer</a>
        </div>
        {% else %}
        {# alert #}
        <div class="alert alert-warning mt-5 mb-5" role="alert">
        Les Leçons sont en cours de préparation
        </div>
        {% endif %}
    </div>
{% endblock %}

templates/home/courses.html.twig
{% extends 'base.html.twig' %}

{% block title %}Philosophie{% endblock %}

{% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
{{ parent() }}
{% endblock %}

{% block body %}
	<!-- header provisoire -->
	<div class="header-provisoire mb-5 d-flex justify-content-center align-items-center">
		<div class="header-provisoire-title">Courses</div>
	</div>
	<!-- cards -->
	<div class="content pt-4 pb-4 mb-5">
		<div class="container">
			<div class="row">
				{% for courses in cours %}
				<div style="width: 18rem;">
					<div class="card mx-sm-auto mx-lg-1 mb-4" >
						{% if courses.mainImage.src == null %}
						<img src="https://via.placeholder.com/300x300?text=Coming+Soon" class="card-img-top" alt="...">
						{% else %}
						<img src="{{ uploaded_asset(courses.mainImage.src) }}" class="card-img-top" alt="...">
						{% endif %}
						<div class="card-body text-center">
							<h5 class="card-title text-center">{{ courses.titre }}</h5>
							<small class="text-muted">crée le {{ courses.createdAt|date('Y-m-d') }}</small>
							<p style="font-size:13px;line-height:1.5rem;text-align:justify" class="mb-3">{% if courses.resume is not null %}{{ courses.resume[0:100] }}...{% endif %}</p>
							<div class="d-flex justify-content-center">
								{# <p class="card-text mb-2">{{ courses.description[0:130]|raw }}...</p> #}
								<a href="{{ path('show_cours', {id:courses.id}) }}" class="btn btn-primary">Voir</a>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				<div class="d-flex justify-content-center mt-4">{{ knp_pagination_render(cours) }}</div>
			</div>
		</div>
	</div>
	<!-- footer -->
	<footer id="footer">
		<div class="container">
			<section>
				<article class="col-1">
					<h3>Contact</h3>
					<ul>
						<li class="address"><a href="#">151 W Adams St<br>Detroit, MI 48226</a></li>
						<li class="mail"><a href="#">contact@harrisonuniversity.com</a></li>
						<li class="phone last"><a href="#">(971) 536 845 924</a></li>
					</ul>
				</article>
				<article class="col-2">
					<h3>Forum topics</h3>
					<ul>
						<li><a href="#">Omnis iste natus error sit</a></li>
						<li><a href="#">Nam libero tempore cum soluta</a></li>
						<li><a href="#">Totam rem aperiam eaque </a></li>
						<li><a href="#">Ipsa quae ab illo inventore veritatis </a></li>
						<li class="last"><a href="#">Architecto beatae vitae dicta sunt </a></li>
					</ul>
				</article>
				<article class="col-3">
					<h3>Social media</h3>
					<p>Temporibus autem quibusdam et aut debitis aut rerum necessitatibus saepe.</p>
					<ul>
						<li class="facebook"><a href="#">Facebook</a></li>
						<li class="google-plus"><a href="#">Google+</a></li>
						<li class="twitter"><a href="#">Twitter</a></li>
						<li class="pinterest"><a href="#">Pinterest</a></li>
					</ul>
				</article>
				<article class="col-4">
					<h3>Newsletter</h3>
					<p>Assumenda est omnis dolor repellendus temporibus autem quibusdam.</p>
					<form action="#">
						<input placeholder="Email address..." type="text">
						<button type="submit">Subscribe</button>
					</form>
					<ul>
						<li><a href="#"></a></li>
					</ul>
				</article>
			</section>
			<p class="copy">Copyright 2014 Harrison High School. Designed by <a href="http://www.vandelaydesign.com/" title="Designed by Vandelay Design" target="_blank">Vandelay Design</a>. All rights reserved.</p>
		</div>
		<!-- / container -->
	</footer>
	<!-- / footer -->

	<div id="fancy">
		<h2>Request information</h2>
		<form action="#">
			<div class="left">
				<fieldset class="mail"><input placeholder="Email address..." type="text"></fieldset>
				<fieldset class="name"><input placeholder="Name..." type="text"></fieldset>
				<fieldset class="subject"><select><option>Choose subject...</option><option>Choose subject...</option><option>Choose subject...</option></select></fieldset>
			</div>
			<div class="right">
				<fieldset class="question"><textarea placeholder="Question..."></textarea></fieldset>
			</div>
			<div class="btn-holder">
				<button class="btn blue" type="submit">Send request</button>
			</div>
		</form>
	</div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Philosophie{% endblock %}

{% block body %}
	
	<div class="slider">
		<ul class="bxslider">
			<li>
				<div class="container">
					<div class="info">
						<h2>It’s Time to <br><span>Get back to school</span></h2>
						<a href="#">Check out our new programs</a>
					</div>
				</div>
				<!-- / content -->
			</li>
			<li>
				<div class="container">
					<div class="info">
						<h2>It’s Time to <br><span>Get back to school</span></h2>
						<a href="#">Check out our new programs</a>
					</div>
				</div>
				<!-- / content -->
			</li>
			<li>
				<div class="container">
					<div class="info">
						<h2>It’s Time to <br><span>Get back to school</span></h2>
						<a href="#">Check out our new programs</a>
					</div>
				</div>
				<!-- / content -->
			</li>
		</ul>
		<div class="bg-bottom"></div>
	</div>
	
	<section class="posts">
		<div class="container">
			<article>
				<div class="pic"><img width="121" src="images/2.png" alt=""></div>
				<div class="info">
					<h3>The best learning methods</h3>
					<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis quasi architecto beatae vitae dicta sunt explicabo. </p>
				</div>
			</article>
			<article>
				<div class="pic"><img width="121" src="images/3.png" alt=""></div>
				<div class="info">
					<h3>Awesome results of our students</h3>
					<p>Vero eos et accusamus et iusto odio dignissimos ducimus blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa.</p>
				</div>
			</article>
		</div>
		<!-- / container -->
	</section>

	<section class="news">
		<div class="container">
			<h2>Latest news</h2>
			<article>
				<div class="pic"><img src="images/1.png" alt=""></div>
				<div class="info">
					<h4>Omnis iste natus error sit voluptatem accusantium </h4>
					<p class="date">14 APR 2014, Jason Bang</p>
					<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores (...)</p>
					<a class="more" href="#">Read more</a>
				</div>
			</article>
			<article>
				<div class="pic"><img src="images/1_1.png" alt=""></div>
				<div class="info">
					<h4>Omnis iste natus error sit voluptatem accusantium </h4>
					<p class="date">14 APR 2014, Jason Bang</p>
					<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores (...)</p>
					<a class="more" href="#">Read more</a>
				</div>
			</article>
			<div class="btn-holder">
				<a class="btn" href="#">See archival news</a>
			</div>
		</div>
		<!-- / container -->
	</section>

	<section class="events">
		<div class="container">
			<h2>Upcoming events</h2>
			<article>
				<div class="current-date">
					<p>April</p>
					<p class="date">15</p>
				</div>
				<div class="info">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
					<a class="more" href="#">Read more</a>
				</div>
			</article>
			<article>
				<div class="current-date">
					<p>April</p>
					<p class="date">17</p>
				</div>
				<div class="info">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
					<a class="more" href="#">Read more</a>
				</div>
			</article>
			<article>
				<div class="current-date">
					<p>April</p>
					<p class="date">25</p>
				</div>
				<div class="info">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
					<a class="more" href="#">Read more</a>
				</div>
			</article>
			<article>
				<div class="current-date">
					<p>April</p>
					<p class="date">29</p>
				</div>
				<div class="info">
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad.</p>
					<a class="more" href="#">Read more</a>
				</div>
			</article>
			<div class="btn-holder">
				<a class="btn blue" href="#">See all upcoming events</a>
			</div>
		</div>
		<!-- / container -->
	</section>
	<div class="container">
		<a href="#fancy" class="info-request">
			<span class="holder">
				<span class="title">Request information</span>
				<span class="text">Do you have some questions? Fill the form and get an answer!</span>
			</span>
			<span class="arrow"></span>
		</a>
	</div>
	
{% endblock %}

templates/home/lesson.html.twig
{% extends 'base.html.twig' %}

{% block title %}Philosophie{% endblock %}

{% block stylesheets %}
<script src="https://kit.fontawesome.com/1596c4b58a.js" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
{{ parent() }}
{% endblock %}

{% block body %}
	<!-- header provisoire -->
	<div class="header-provisoire mb-5 d-flex justify-content-center align-items-center">
		<div class="header-provisoire-title">Lesson</div>
	</div>
	<div class="content">
		<div class="container">
			<div class="mb-5 row">
				{% if lesson.orderId == 1 %}
				<div class="col-6 d-flex justify-content-start">
					<a href="{{ path('show_cours', {id:lesson.cours.id}) }}" type="button" class="btn btn-secondary"><i class="fas fa-chevron-left"></i> Introduction </a> 
				</div>
				{% endif %}
				{% if before.orderId is defined %}
				<div class="{% if after.orderId is defined %}col-6{% else %}col-12{% endif %} d-flex justify-content-start">
					<a href="{{ path('lesson_show', {slug: slug, order:before.orderId}) }}" type="button" class="btn btn-secondary"><i class="fas fa-chevron-left"></i> {{ before.title }}</a>
				</div>
				{% endif %}
				{% if after.orderId is defined %}
				<div class="col-6 d-flex justify-content-end">
					<a href="{{ path('lesson_show', {slug: slug, order:after.orderId}) }}" type="button" class="d-block btn btn-secondary">{{ after.title }} <i class="fas fa-chevron-right"></i></a>
				</div>
				{% endif %}
			</div>
		</div>
		<div class="container">
			{# flash message #}
			{% for message in app.flashes('notice') %}
				<div class="alert alert-success" role="alert">
					{{ message }}
				</div>
			{% endfor %}

			<div class="lesson main-content mb-5">
				{# title #}
				<h1 class="mb-4">
					{{ lesson.orderId }}. {{ lesson.title }} 
					{% if is_granted("ROLE_ADMIN") %}
					<a href="{{ path('lesson_edit', {'id': lesson.id}) }}" class="btn btn-warning">Modifier</a>
					{% endif %}
				</h1>
				{# contet  #}
				{{ lesson.content|raw }}
				<div style="display:flex;justify-content:center;width:100%;">
					{% if lesson.completed == false %}
					<form method="post" action="{{ path('completed', {'id': lesson.id, 'value' : '1'}) }}">
						<input type="hidden" name="completed">
						<button class="btn btn-primary">Indiquer la leçon comme terminée</button>
					</form>
					{% else %}
					<form method="post" action="{{ path('completed', {'id': lesson.id, 'value' : '0'}) }}">
						<input type="hidden" name="completed">
						<button class="btn btn-success">Indiquer que la leçon est en cours</button>
					</form>
					{% endif %}
				</div>
			</div><br>

			<aside id="sidebar">
				<div>
					<h2 class="mb-4">Sommaire</h2>
					<p class="mb-3"><a href="{{ path('show_cours', {id:lesson.cours.id}) }}" type="button" class="sidebar-p"> Introduction </a></p>
					{% for lessons in lessons %}
					<p class="mb-3"><a href="{{ path('lesson_show', {slug: slug, order:lessons.orderId}) }}" class="sidebar-p {% if lessons.completed == true %} completed {% endif %}">{{ lessons.title }}</a></p>
					{% endfor %}
				</div>
			</aside>
			<!-- / sidebar -->
	
		</div>
		<!-- / container -->
	</div>
	
	<footer id="footer">
		<div class="container">
			<section>
				<article class="col-1">
					<h3>Contact</h3>
					<ul>
						<li class="address"><a href="#">151 W Adams St<br>Detroit, MI 48226</a></li>
						<li class="mail"><a href="#">contact@harrisonuniversity.com</a></li>
						<li class="phone last"><a href="#">(971) 536 845 924</a></li>
					</ul>
				</article>
				<article class="col-2">
					<h3>Forum topics</h3>
					<ul>
						<li><a href="#">Omnis iste natus error sit</a></li>
						<li><a href="#">Nam libero tempore cum soluta</a></li>
						<li><a href="#">Totam rem aperiam eaque </a></li>
						<li><a href="#">Ipsa quae ab illo inventore veritatis </a></li>
						<li class="last"><a href="#">Architecto beatae vitae dicta sunt </a></li>
					</ul>
				</article>
				<article class="col-3">
					<h3>Social media</h3>
					<p>Temporibus autem quibusdam et aut debitis aut rerum necessitatibus saepe.</p>
					<ul>
						<li class="facebook"><a href="#">Facebook</a></li>
						<li class="google-plus"><a href="#">Google+</a></li>
						<li class="twitter"><a href="#">Twitter</a></li>
						<li class="pinterest"><a href="#">Pinterest</a></li>
					</ul>
				</article>
				<article class="col-4">
					<h3>Newsletter</h3>
					<p>Assumenda est omnis dolor repellendus temporibus autem quibusdam.</p>
					<form action="#">
						<input placeholder="Email address..." type="text">
						<button type="submit">Subscribe</button>
					</form>
					<ul>
						<li><a href="#"></a></li>
					</ul>
				</article>
			</section>
			<p class="copy">Copyright 2014 Harrison High School. Designed by <a href="http://www.vandelaydesign.com/" title="Designed by Vandelay Design" target="_blank">Vandelay Design</a>. All rights reserved.</p>
		</div>
		<!-- / container -->
	</footer>
	<!-- / footer -->

	<div id="fancy">
		<h2>Request information</h2>
		<form action="#">
			<div class="left">
				<fieldset class="mail"><input placeholder="Email address..." type="text"></fieldset>
				<fieldset class="name"><input placeholder="Name..." type="text"></fieldset>
				<fieldset class="subject"><select><option>Choose subject...</option><option>Choose subject...</option><option>Choose subject...</option></select></fieldset>
			</div>
			<div class="right">
				<fieldset class="question"><textarea placeholder="Question..."></textarea></fieldset>
			</div>
			<div class="btn-holder">
				<button class="btn blue" type="submit">Send request</button>
			</div>
		</form>
	</div>
{% endblock %}
{% block javascripts %}
{{ parent() }}
<script src="{{ asset('/js/myscript.js') }}"></script>
{% endblock %}